"""empty message

Revision ID: 113b3ac6355f
Revises: 568a1c315cfb
Create Date: 2016-06-08 12:00:04.639525

"""

# revision identifiers, used by Alembic.
revision = '113b3ac6355f'
down_revision = '568a1c315cfb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Class_schedule', sa.Column('deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Class_schedule', 'deleted')
    ### end Alembic commands ###
