"""empty message

Revision ID: 1143be668b05
Revises: 32076d6d8dcf
Create Date: 2016-05-19 13:21:41.079490

"""

# revision identifiers, used by Alembic.
revision = '1143be668b05'
down_revision = '32076d6d8dcf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Newsletter_subscriber', sa.Column('subscribe_reason', sa.Enum('newsletter_signup', 'contact_page_email', 'created_login', 'admin_registered', 'bought_gc', 'class_signup', name='subscribe_reason'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Newsletter_subscriber', 'subscribe_reason')
    ### end Alembic commands ###
