"""Add new fields to product inventory

Revision ID: 1203b0fa5802
Revises: 21a5251bf476
Create Date: 2016-01-17 08:55:23.045566

"""

# revision identifiers, used by Alembic.
revision = '1203b0fa5802'
down_revision = '21a5251bf476'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shop_productinventory', sa.Column('quantity_stocked', sa.Integer(), nullable=True))
    op.alter_column('Shop_productinventory', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text(u"'1'"))
    op.alter_column('Shop_productinventory', 'campus_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('Shop_productinventory', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('Shop_productinventory', 'quantity_to_stock',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               existing_server_default=sa.text(u"'0'"),
               nullable=True)
    op.drop_index('Shop_productinventory_campus_id', table_name='Shop_productinventory')
    op.drop_index('Shop_productinventory_product_id', table_name='Shop_productinventory')
    op.create_foreign_key(None, 'Shop_productinventory', 'Shop_product', ['product_id'], ['product_id'])
    op.create_foreign_key(None, 'Shop_productinventory', 'Class_campus', ['campus_id'], ['campus_id'])
    op.add_column('Shop_productinventoryitem', sa.Column('blame', sa.Integer(), nullable=True))
    op.add_column('Shop_productinventoryitem', sa.Column('reason', sa.Integer(), nullable=True))
    op.add_column('Shop_productinventoryitem', sa.Column('to_campus', sa.Integer(), nullable=True))
    op.alter_column('Shop_productinventoryitem', 'campus_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('Shop_productinventoryitem', 'date_stocked',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('Shop_productinventoryitem', 'inventory_adjustment',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('Shop_productinventoryitem', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('Shop_productinventoryitem', 'quantity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_index('Shop_productinventoryitem_campus_id', table_name='Shop_productinventoryitem')
    op.drop_index('Shop_productinventoryitem_product_id', table_name='Shop_productinventoryitem')
    op.create_foreign_key(None, 'Shop_productinventoryitem', 'Class_campus', ['campus_id'], ['campus_id'])
    op.create_foreign_key(None, 'Shop_productinventoryitem', 'auth_user', ['blame'], ['id'])
    op.create_foreign_key(None, 'Shop_productinventoryitem', 'Class_campus', ['to_campus'], ['campus_id'])
    op.create_foreign_key(None, 'Shop_productinventoryitem', 'Shop_product', ['product_id'], ['product_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Shop_productinventoryitem', type_='foreignkey')
    op.drop_constraint(None, 'Shop_productinventoryitem', type_='foreignkey')
    op.drop_constraint(None, 'Shop_productinventoryitem', type_='foreignkey')
    op.drop_constraint(None, 'Shop_productinventoryitem', type_='foreignkey')
    op.create_index('Shop_productinventoryitem_product_id', 'Shop_productinventoryitem', ['product_id'], unique=False)
    op.create_index('Shop_productinventoryitem_campus_id', 'Shop_productinventoryitem', ['campus_id'], unique=False)
    op.alter_column('Shop_productinventoryitem', 'quantity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('Shop_productinventoryitem', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('Shop_productinventoryitem', 'inventory_adjustment',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('Shop_productinventoryitem', 'date_stocked',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('Shop_productinventoryitem', 'campus_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('Shop_productinventoryitem', 'to_campus')
    op.drop_column('Shop_productinventoryitem', 'reason')
    op.drop_column('Shop_productinventoryitem', 'blame')
    op.drop_constraint(None, 'Shop_productinventory', type_='foreignkey')
    op.drop_constraint(None, 'Shop_productinventory', type_='foreignkey')
    op.create_index('Shop_productinventory_product_id', 'Shop_productinventory', ['product_id'], unique=False)
    op.create_index('Shop_productinventory_campus_id', 'Shop_productinventory', ['campus_id'], unique=False)
    op.alter_column('Shop_productinventory', 'quantity_to_stock',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)
    op.alter_column('Shop_productinventory', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('Shop_productinventory', 'campus_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('Shop_productinventory', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text(u"'1'"))
    op.drop_column('Shop_productinventory', 'quantity_stocked')
    op.create_table('backup_Class_description',
    sa.Column('description_id', mysql.INTEGER(display_width=11), server_default=sa.text(u"'0'"), autoincrement=False, nullable=False),
    sa.Column('order', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('abbr', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.LONGTEXT(), nullable=False),
    sa.Column('menu', mysql.LONGTEXT(), nullable=False),
    sa.Column('knife_level', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('veggie_level', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('dairy_level', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('wheat_level', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('cost_override', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('wine', mysql.VARCHAR(length=255), nullable=False),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('gift_certificate',
    sa.Column('certificate_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('campus_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('sender_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sender_email', mysql.VARCHAR(length=75), nullable=True),
    sa.Column('sender_phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('amount_to_give', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('recipient_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('recipient_email', mysql.VARCHAR(length=75), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('giftcard', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('date_sent', sa.DATE(), nullable=True),
    sa.Column('name_on_envelope', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('street_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('zip_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('creditcard_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('paid_with', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('expiration_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], [u'Class_campus.campus_id'], name=u'gift_certificate_ibfk_1'),
    sa.PrimaryKeyConstraint('certificate_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
