"""empty message

Revision ID: 14108430f122
Revises: 303ff4ac84fd
Create Date: 2015-10-27 01:40:42.872993

"""

# revision identifiers, used by Alembic.
revision = '14108430f122'
down_revision = '303ff4ac84fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shop_product', sa.Column('active', sa.Boolean(), nullable=True, server_default="1"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shop_product', 'active')
    ### end Alembic commands ###
