"""empty message

Revision ID: 15270308e5ab
Revises: 3316b850d631
Create Date: 2015-10-14 18:03:28.421970

"""

# revision identifiers, used by Alembic.
revision = '15270308e5ab'
down_revision = '3316b850d631'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_order', sa.Column('interested_in_assisting', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_order', 'interested_in_assisting')
    ### end Alembic commands ###
