"""empty message

Revision ID: 18a086c0e3c
Revises: 1143be668b05
Create Date: 2016-06-02 10:56:36.972501

"""

# revision identifiers, used by Alembic.
revision = '18a086c0e3c'
down_revision = '1143be668b05'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Class_campus', sa.Column('private_class_policy', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Class_campus', 'private_class_policy')
    ### end Alembic commands ###
