"""Add Admin note table (used for "notes from Monika")

Revision ID: 1925c010afff
Revises: 3f74e0385042
Create Date: 2015-12-07 22:06:47.495489

"""

# revision identifiers, used by Alembic.
revision = '1925c010afff'
down_revision = '3f74e0385042'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [u'auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_note_ts', 'admin_note', ['ts'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_note_ts', table_name='admin_note')
    op.drop_table('admin_note')
    ### end Alembic commands ###
