"""empty message

Revision ID: 238f06feea3e
Revises: 3c4f0c104719
Create Date: 2016-06-17 10:12:03.648203

"""

# revision identifiers, used by Alembic.
revision = '238f06feea3e'
down_revision = '3c4f0c104719'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# custom imports
from sqlalchemy import event
from sqlalchemy.orm import sessionmaker, Session as BaseSession
from flask_sqlalchemy import _SessionSignalEvents
from hipcooks import models

try:
    event.remove(BaseSession, 'before_commit', _SessionSignalEvents.session_signal_before_commit)
    event.remove(BaseSession, 'after_commit', _SessionSignalEvents.session_signal_after_commit)
    event.remove(BaseSession, 'after_rollback', _SessionSignalEvents.session_signal_after_rollback)
except:
    pass

Session = sessionmaker()


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    current_text_map = {}
    bind = op.get_bind()
    session = Session(bind=bind)
    campus_data = session.execute('SELECT campus_id, private_class_policy FROM Class_campus;').fetchall()
    for campus_tuple in campus_data:
        current_text_map[campus_tuple[0]] = campus_tuple[1]

    op.add_column('Class_campus', sa.Column('private_class_page_policy_text', sa.Text(), nullable=True))
    op.add_column('Class_campus', sa.Column('private_class_page_text', sa.Text(), nullable=True))
    op.drop_column('Class_campus', 'private_class_policy')

    for campus in session.query(models.Campus).all():
        campus.private_class_page_policy_text = current_text_map[campus.id]
        session.add(campus)

    session.commit()

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Class_campus', sa.Column('private_class_policy', mysql.TEXT(), nullable=True))
    op.drop_column('Class_campus', 'private_class_page_text')
    op.drop_column('Class_campus', 'private_class_page_policy_text')
    ### end Alembic commands ###
