"""empty message

Revision ID: 261441defc5e
Revises: 366936225974
Create Date: 2016-05-03 09:28:01.502546

"""

# revision identifiers, used by Alembic.
revision = '261441defc5e'
down_revision = '366936225974'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_prep_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_prep_list_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pre_prep_list_id', sa.Integer(), nullable=True),
    sa.Column('setup_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pre_prep_list_id'], [u'pre_prep_list.id'], ),
    sa.ForeignKeyConstraint(['setup_id'], [u'setup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pre_prep_list_item')
    op.drop_table('pre_prep_list')
    ### end Alembic commands ###
