"""Rename total column to avoid confusion

Revision ID: 2975cdce0128
Revises: 306030498dbe
Create Date: 2015-10-29 19:06:03.530389

"""

# revision identifiers, used by Alembic.
revision = '2975cdce0128'
down_revision = '306030498dbe'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_certificate_block', sa.Column('total_certs', sa.Integer(), nullable=True))
    op.drop_column('gift_certificate_block', 'total')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_certificate_block', sa.Column('total', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('gift_certificate_block', 'total_certs')
    ### end Alembic commands ###
