"""empty message

Revision ID: 2acf9586f06f
Revises: 1ab7f35b9c6
Create Date: 2015-10-13 23:41:43.376865

"""

# revision identifiers, used by Alembic.
revision = '2acf9586f06f'
down_revision = '1ab7f35b9c6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_rating', sa.Integer(), nullable=True),
    sa.Column('assistant_rating', sa.Integer(), nullable=True),
    sa.Column('group_comments', sa.Text(), nullable=True),
    sa.Column('food_comments', sa.Text(), nullable=True),
    sa.Column('pacing_rating', sa.Integer(), nullable=True),
    sa.Column('pacing_comments', sa.Text(), nullable=True),
    sa.Column('tasting_rating', sa.Integer(), nullable=True),
    sa.Column('tasting_comments', sa.Text(), nullable=True),
    sa.Column('ingredients_problems', sa.Boolean(), nullable=True),
    sa.Column('ingredients_comments', sa.Text(), nullable=True),
    sa.Column('preprep_rating', sa.Integer(), nullable=True),
    sa.Column('preprep_comments', sa.Text(), nullable=True),
    sa.Column('breakage_rating', sa.Integer(), nullable=True),
    sa.Column('breakage_comments', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('sent_on', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], [u'Class_schedule.schedule_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extra_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('how_paid', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], [u'Class_schedule.schedule_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_report_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], [u'class_report.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('foo')
    op.alter_column('gift_certificate_order', 'amount_to_give',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('gift_certificate_order', 'campus_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('gift_certificate_order', 'delivery_method',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('gift_certificate_order', 'recipient_email',
               existing_type=mysql.VARCHAR(length=75),
               nullable=True)
    op.alter_column('gift_certificate_order', 'recipient_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('gift_certificate_order', 'sender_email',
               existing_type=mysql.VARCHAR(length=75),
               nullable=True)
    op.alter_column('gift_certificate_order', 'sender_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('gift_certificate_order', 'sender_phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('shopping_list_instance', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'shopping_list_instance_item', 'Class_campus', ['campus_id'], ['campus_id'])
    op.alter_column('shopping_list_instance_item_map', 'quantity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('shopping_list_instance_item_map', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_instance_item_map', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    op.alter_column('shopping_list_instance_item_map', 'quantity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'shopping_list_instance_item', type_='foreignkey')
    op.alter_column('shopping_list_instance', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('gift_certificate_order', 'sender_phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('gift_certificate_order', 'sender_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('gift_certificate_order', 'sender_email',
               existing_type=mysql.VARCHAR(length=75),
               nullable=False)
    op.alter_column('gift_certificate_order', 'recipient_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('gift_certificate_order', 'recipient_email',
               existing_type=mysql.VARCHAR(length=75),
               nullable=False)
    op.alter_column('gift_certificate_order', 'delivery_method',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('gift_certificate_order', 'campus_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('gift_certificate_order', 'amount_to_give',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_table('foo',
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('guests', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cancelled', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('class_report_comment')
    op.drop_table('extra_person')
    op.drop_table('class_report')
    ### end Alembic commands ###
