"""Add role name to teacher campus.

Revision ID: 2bc59024f9e9
Revises: 439cca6d4887
Create Date: 2015-11-24 17:04:25.927350

"""

# revision identifiers, used by Alembic.
revision = '2bc59024f9e9'
down_revision = '235f19642cb6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Class_campus', 'directions',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('Class_campus', 'embed_url',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.add_column('Class_teacher_campuses', sa.Column('role_name', sa.String(length=30), nullable=True))
    op.alter_column('Class_teacher_campuses', 'campus_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('Class_teacher_campuses', 'teacher_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_index('campus_id_refs_campus_id_73554e7374394adc', table_name='Class_teacher_campuses')
    op.drop_index('teacher_id', table_name='Class_teacher_campuses')
    op.create_foreign_key(None, 'Class_teacher_campuses', 'Class_teacher', ['teacher_id'], ['user_id'])
    op.create_foreign_key(None, 'Class_teacher_campuses', 'Class_campus', ['campus_id'], ['campus_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Class_teacher_campuses', type_='foreignkey')
    op.drop_constraint(None, 'Class_teacher_campuses', type_='foreignkey')
    op.create_index('teacher_id', 'Class_teacher_campuses', ['teacher_id', 'campus_id'], unique=True)
    op.create_index('campus_id_refs_campus_id_73554e7374394adc', 'Class_teacher_campuses', ['campus_id'], unique=False)
    op.alter_column('Class_teacher_campuses', 'teacher_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('Class_teacher_campuses', 'campus_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('Class_teacher_campuses', 'role_name')
    op.alter_column('Class_campus', 'embed_url',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('Class_campus', 'directions',
               existing_type=mysql.TEXT(),
               nullable=False)
    ### end Alembic commands ###
