"""Add an active column to photos.

Revision ID: 2d4ea6b57d6e
Revises: 57d0aa35f4d2
Create Date: 2016-03-06 07:42:16.723965

"""

# revision identifiers, used by Alembic.
revision = '2d4ea6b57d6e'
down_revision = '57d0aa35f4d2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Class_album', sa.Column('active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Class_album', 'active')
    ### end Alembic commands ###
