"""Added gift certificate blocks to strengthen the relationships between gift certs in the same block

Revision ID: 306030498dbe
Revises: 28d05411ce1b
Create Date: 2015-10-29 18:22:51.322415

"""

# revision identifiers, used by Alembic.
revision = '306030498dbe'
down_revision = '28d05411ce1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_certificate_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.Column('sender_name', sa.String(length=100), nullable=True),
    sa.Column('sender_email', sa.String(length=75), nullable=True),
    sa.Column('sender_phone', sa.String(length=20), nullable=True),
    sa.Column('amount_to_give', sa.Integer(), nullable=True),
    sa.Column('recipient_name', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('date_sent', sa.Date(), nullable=True),
    sa.Column('paid_with', sa.String(length=10), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], [u'Class_campus.campus_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Shop_giftcertificate', sa.Column('block_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Shop_giftcertificate', 'gift_certificate_block', ['block_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Shop_giftcertificate', type_='foreignkey')
    op.drop_column('Shop_giftcertificate', 'block_id')
    op.drop_table('gift_certificate_block')
    ### end Alembic commands ###
