"""empty message

Revision ID: 31be75e1fa29
Revises: 113b3ac6355f
Create Date: 2016-06-13 10:31:47.987916

"""

# revision identifiers, used by Alembic.
revision = '31be75e1fa29'
down_revision = '113b3ac6355f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Class_teacher', sa.Column('active', sa.Boolean(), nullable=True, server_default='1'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Class_teacher', 'active')
    ### end Alembic commands ###
