"""empty message

Revision ID: 32076d6d8dcf
Revises: 2eb7b5bbf022
Create Date: 2016-05-18 09:25:16.436226

"""

# revision identifiers, used by Alembic.
revision = '32076d6d8dcf'
down_revision = '2eb7b5bbf022'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guest_order', 'email',
               existing_type=mysql.VARCHAR(length=75),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guest_order', 'email',
               existing_type=mysql.VARCHAR(length=75),
               nullable=False)
    ### end Alembic commands ###
