"""empty message

Revision ID: 33232fa6a9b8
Revises: 1135a454bb84
Create Date: 2016-07-06 13:40:55.514381

"""

# revision identifiers, used by Alembic.
revision = '33232fa6a9b8'
down_revision = '1135a454bb84'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shop_product', sa.Column('kitchen_column', sa.Integer(), nullable=True))
    op.add_column('Shop_product', sa.Column('kitchen_row', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shop_product', 'kitchen_row')
    op.drop_column('Shop_product', 'kitchen_column')
    ### end Alembic commands ###
