"""empty message

Revision ID: 342828f129b9
Revises: 48fc7ba887aa
Create Date: 2016-04-15 11:17:46.851426

"""

# revision identifiers, used by Alembic.
revision = '342828f129b9'
down_revision = '48fc7ba887aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setup', sa.Column('last_updated', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setup', 'last_updated')
    ### end Alembic commands ###
