"""Put in a "splash type" that determines which item in a type shows up

Revision ID: 35273b6bffa7
Revises: 4f786f3c132b
Create Date: 2016-03-20 07:16:03.922149

"""

# revision identifiers, used by Alembic.
revision = '35273b6bffa7'
down_revision = '4f786f3c132b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shop_product', sa.Column('splash_type', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shop_product', 'splash_type')
    ### end Alembic commands ###
