"""empty message

Revision ID: 366936225974
Revises: f45baecadb0
Create Date: 2016-04-20 11:15:06.441948

"""

# revision identifiers, used by Alembic.
revision = '366936225974'
down_revision = 'f45baecadb0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_instance_item', sa.Column('category', sa.String(length=10), nullable=True))
    op.add_column('shopping_list_instance_item', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shopping_list_instance_item', 'Class_description', ['class_id'], ['description_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_list_instance_item', type_='foreignkey')
    op.drop_column('shopping_list_instance_item', 'class_id')
    op.drop_column('shopping_list_instance_item', 'category')
    ### end Alembic commands ###
