"""Added certificate block name to allow commenting.

Revision ID: 38a549a5b880
Revises: 2975cdce0128
Create Date: 2015-10-29 19:23:06.399239

"""

# revision identifiers, used by Alembic.
revision = '38a549a5b880'
down_revision = '2975cdce0128'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_certificate_block', sa.Column('name', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gift_certificate_block', 'name')
    ### end Alembic commands ###
