"""Add created to schedule order

Revision ID: 3d3b3f2ec107
Revises: 34dac5f1aa6c
Create Date: 2016-01-30 09:13:42.416893

"""

# revision identifiers, used by Alembic.
revision = '3d3b3f2ec107'
down_revision = '34dac5f1aa6c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from hipcooks import models, db
from datetime import datetime

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_order', sa.Column('created', sa.DateTime(), nullable=True))
    db.session.execute(models.ScheduleOrder.__table__.update().values(
                        created=datetime.now()
                    )
    )
    
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_order', 'created')
    op.create_table('backup_Class_description',
    sa.Column('description_id', mysql.INTEGER(display_width=11), server_default=sa.text(u"'0'"), autoincrement=False, nullable=False),
    sa.Column('order', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('abbr', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.LONGTEXT(), nullable=False),
    sa.Column('menu', mysql.LONGTEXT(), nullable=False),
    sa.Column('knife_level', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('veggie_level', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('dairy_level', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('wheat_level', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('cost_override', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('wine', mysql.VARCHAR(length=255), nullable=False),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('gift_certificate',
    sa.Column('certificate_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('campus_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('sender_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sender_email', mysql.VARCHAR(length=75), nullable=True),
    sa.Column('sender_phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('amount_to_give', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('recipient_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('recipient_email', mysql.VARCHAR(length=75), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('giftcard', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('date_sent', sa.DATE(), nullable=True),
    sa.Column('name_on_envelope', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('street_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('zip_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('creditcard_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('paid_with', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('expiration_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], [u'Class_campus.campus_id'], name=u'gift_certificate_ibfk_1'),
    sa.PrimaryKeyConstraint('certificate_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
