"""Prep product tables for new site's product sale model

Revision ID: 3e9b19c9e07c
Revises: 4e2abc6d63e6
Create Date: 2015-10-22 06:14:58.144114

"""

# revision identifiers, used by Alembic.
revision = '3e9b19c9e07c'
down_revision = '1c1b8b26cad5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    op.alter_column('Shop_product', 'available_to_ship',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('Shop_product', 'cost_to_ship',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               nullable=True)
    op.alter_column('Shop_product', 'price',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               nullable=True)
#    op.drop_index('Shop_product_photo_id', table_name='Shop_product')
#    op.create_foreign_key(None, 'Shop_product', 'Class_photo', ['photo_id'], ['photo_id'])
    op.add_column('Shop_productsale', sa.Column('purchase_id', sa.Integer(), nullable=True))
    op.drop_index('Shop_productsale_campus_id', table_name='Shop_productsale')
    op.drop_index('Shop_productsale_creditcard_id', table_name='Shop_productsale')
    op.drop_index('Shop_productsale_sold_by_id', table_name='Shop_productsale')
    op.create_foreign_key(None, 'Shop_productsale', 'purchase', ['purchase_id'], ['id'])
    op.create_foreign_key(None, 'Shop_productsale', 'auth_user', ['sold_by_id'], ['id'])
    op.create_foreign_key(None, 'Shop_productsale', 'Class_campus', ['campus_id'], ['campus_id'])
    op.drop_column('Shop_productsale', 'creditcard_id')
    op.alter_column('Shop_productsaleitem', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('Shop_productsaleitem', 'productsale_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('Shop_productsaleitem', 'quantity',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=True)
    op.alter_column('Shop_productsaleitem', 'shipping',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               nullable=True)
    op.alter_column('Shop_productsaleitem', 'tax',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               nullable=True)
    op.alter_column('Shop_productsaleitem', 'total_amount',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               nullable=True)
    op.drop_index('Shop_productsaleitem_product_id', table_name='Shop_productsaleitem')
    op.drop_index('Shop_productsaleitem_productsale_id', table_name='Shop_productsaleitem')
    op.create_foreign_key(None, 'Shop_productsaleitem', 'Shop_product', ['product_id'], ['product_id'])
    op.create_foreign_key(None, 'Shop_productsaleitem', 'Shop_productsale', ['productsale_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Shop_productsaleitem', type_='foreignkey')
    op.drop_constraint(None, 'Shop_productsaleitem', type_='foreignkey')
    op.create_index('Shop_productsaleitem_productsale_id', 'Shop_productsaleitem', ['productsale_id'], unique=False)
    op.create_index('Shop_productsaleitem_product_id', 'Shop_productsaleitem', ['product_id'], unique=False)
    op.alter_column('Shop_productsaleitem', 'total_amount',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               nullable=False)
    op.alter_column('Shop_productsaleitem', 'tax',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               nullable=False)
    op.alter_column('Shop_productsaleitem', 'shipping',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               nullable=False)
    op.alter_column('Shop_productsaleitem', 'quantity',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               nullable=False)
    op.alter_column('Shop_productsaleitem', 'productsale_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('Shop_productsaleitem', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('Shop_productsale', sa.Column('creditcard_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Shop_productsale', type_='foreignkey')
    op.drop_constraint(None, 'Shop_productsale', type_='foreignkey')
    op.drop_constraint(None, 'Shop_productsale', type_='foreignkey')
    op.create_index('Shop_productsale_sold_by_id', 'Shop_productsale', ['sold_by_id'], unique=False)
    op.create_index('Shop_productsale_creditcard_id', 'Shop_productsale', ['creditcard_id'], unique=False)
    op.create_index('Shop_productsale_campus_id', 'Shop_productsale', ['campus_id'], unique=False)
    op.drop_column('Shop_productsale', 'purchase_id')
    op.add_column('Shop_product', sa.Column('placement_col', mysql.DECIMAL(precision=2, scale=0), nullable=False))
    op.add_column('Shop_product', sa.Column('placement_row', mysql.DECIMAL(precision=2, scale=0), nullable=False))
    op.drop_constraint(None, 'Shop_product', type_='foreignkey')
    op.create_index('Shop_product_photo_id', 'Shop_product', ['photo_id'], unique=False)
    op.alter_column('Shop_product', 'price',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               nullable=False)
    op.alter_column('Shop_product', 'cost_to_ship',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
    op.alter_column('Shop_product', 'available_to_ship',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_table('product',
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('photo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('available_to_ship', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('cost_to_ship', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], [u'Class_photo.photo_id'], name=u'product_ibfk_1'),
    sa.PrimaryKeyConstraint('product_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
