"""Linked existing gift orders

Revision ID: 42f6c0f8f965
Revises: 3bc1f9a32d6a
Create Date: 2015-10-24 07:23:03.799445

"""

# revision identifiers, used by Alembic.
revision = '42f6c0f8f965'
down_revision = '3bc1f9a32d6a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import logging

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_table('gift_certificate_order')
    except sa.exc.OperationalError:
        logging.warn("Table gift_certificate_order doesn't exist")
        raise
    op.add_column('Shop_giftcertificate', sa.Column('delivery_method', sa.Integer(), nullable=True))
    op.add_column('Shop_giftcertificate', sa.Column('purchase_id', sa.Integer(), nullable=True))
    op.alter_column('Shop_giftcertificate', 'amount_to_give',
               existing_type=mysql.SMALLINT(display_width=5, unsigned=True),
               nullable=True)
    op.alter_column('Shop_giftcertificate', 'campus_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('Shop_giftcertificate', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('Shop_giftcertificate', 'giftcard',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('Shop_giftcertificate', 'message',
               existing_type=mysql.LONGTEXT(),
               nullable=True)
    op.alter_column('Shop_giftcertificate', 'recipient_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('Shop_giftcertificate', 'sender_email',
               existing_type=mysql.VARCHAR(length=75),
               nullable=True)
    op.alter_column('Shop_giftcertificate', 'sender_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_index('Shop_giftcertificate_campus_id', table_name='Shop_giftcertificate')
    op.drop_index('Shop_giftcertificate_creditcard_id', table_name='Shop_giftcertificate')
    op.create_foreign_key(None, 'Shop_giftcertificate', 'purchase', ['purchase_id'], ['id'])
    op.create_foreign_key(None, 'Shop_giftcertificate', 'Class_campus', ['campus_id'], ['campus_id'])
    op.alter_column('Shop_product', 'name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('Shop_product', 'photo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('purchase', sa.Column('address1', sa.String(length=255), nullable=True))
    op.add_column('purchase', sa.Column('address2', sa.String(length=255), nullable=True))
    op.add_column('purchase', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('purchase', sa.Column('country', sa.CHAR(length=2), nullable=True))
    op.add_column('purchase', sa.Column('state', sa.CHAR(length=2), nullable=True))
    op.add_column('purchase', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('purchase', sa.Column('zip_code', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'purchase', 'auth_user', ['user_id'], ['id'])
    op.drop_column('transaction', 'city')
    op.drop_column('transaction', 'first_name')
    op.drop_column('transaction', 'last_name')
    op.drop_column('transaction', 'country')
    op.drop_column('transaction', 'state')
    op.drop_column('transaction', 'street')
    op.drop_column('transaction', 'zip_code')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('zip_code', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('transaction', sa.Column('street', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('transaction', sa.Column('state', mysql.CHAR(length=2), nullable=True))
    op.add_column('transaction', sa.Column('country', mysql.CHAR(length=2), nullable=True))
    op.add_column('transaction', sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('transaction', sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('transaction', sa.Column('city', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_column('purchase', 'zip_code')
    op.drop_column('purchase', 'user_id')
    op.drop_column('purchase', 'state')
    op.drop_column('purchase', 'country')
    op.drop_column('purchase', 'city')
    op.drop_column('purchase', 'address2')
    op.drop_column('purchase', 'address1')
    op.alter_column('Shop_product', 'photo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('Shop_product', 'name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.drop_column('Shop_product', 'placement_row')
    op.drop_column('Shop_product', 'placement_col')
    op.drop_constraint(None, 'Shop_giftcertificate', type_='foreignkey')
    op.drop_constraint(None, 'Shop_giftcertificate', type_='foreignkey')
    op.create_index('Shop_giftcertificate_creditcard_id', 'Shop_giftcertificate', ['creditcard_id'], unique=False)
    op.create_index('Shop_giftcertificate_campus_id', 'Shop_giftcertificate', ['campus_id'], unique=False)
    op.alter_column('Shop_giftcertificate', 'sender_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('Shop_giftcertificate', 'sender_email',
               existing_type=mysql.VARCHAR(length=75),
               nullable=False)
    op.alter_column('Shop_giftcertificate', 'recipient_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('Shop_giftcertificate', 'message',
               existing_type=mysql.LONGTEXT(),
               nullable=False)
    op.alter_column('Shop_giftcertificate', 'giftcard',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('Shop_giftcertificate', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('Shop_giftcertificate', 'campus_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('Shop_giftcertificate', 'amount_to_give',
               existing_type=mysql.SMALLINT(display_width=5, unsigned=True),
               nullable=False)
    op.drop_column('Shop_giftcertificate', 'purchase_id')
    op.drop_column('Shop_giftcertificate', 'delivery_method')
    op.create_table('gift_certificate_order',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('campus_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('purchase_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('gift_certificate_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('delivery_method', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sender_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sender_email', mysql.VARCHAR(length=75), nullable=True),
    sa.Column('sender_phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('amount_to_give', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('recipient_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('recipient_email', mysql.VARCHAR(length=75), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('name_on_envelope', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('street_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('zip_code', mysql.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], [u'Class_campus.campus_id'], name=u'gift_certificate_order_ibfk_1'),
    sa.ForeignKeyConstraint(['gift_certificate_id'], [u'Shop_giftcertificate.certificate_id'], name=u'gift_certificate_order_ibfk_3'),
    sa.ForeignKeyConstraint(['purchase_id'], [u'purchase.id'], name=u'gift_certificate_order_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
