"""Add "Got it" flag that indicates if a shopping list item should be shown in a print view

Revision ID: 433267c1db40
Revises: 54b930c2fbf2
Create Date: 2015-12-08 02:07:51.279352

"""

# revision identifiers, used by Alembic.
revision = '433267c1db40'
down_revision = '54b930c2fbf2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_instance_item', sa.Column('got_it', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list_instance_item', 'got_it')
    ### end Alembic commands ###
