"""empty message

Revision ID: 4367b53299c3
Revises: 512c88e1b54d
Create Date: 2016-06-07 10:23:53.259488

"""

# revision identifiers, used by Alembic.
revision = '4367b53299c3'
down_revision = '512c88e1b54d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Class_schedule', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('Class_schedule', sa.Column('contact_email', sa.String(length=75), nullable=True))
    op.add_column('Class_schedule', sa.Column('contact_name', sa.String(length=255), nullable=True))
    op.add_column('Class_schedule', sa.Column('contact_phone', sa.String(length=20), nullable=True))
    op.add_column('Class_schedule', sa.Column('event_reason', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Class_schedule', 'event_reason')
    op.drop_column('Class_schedule', 'contact_phone')
    op.drop_column('Class_schedule', 'contact_name')
    op.drop_column('Class_schedule', 'contact_email')
    op.drop_column('Class_schedule', 'company_name')
    ### end Alembic commands ###
