"""empty message

Revision ID: 44b2ab3c0bb7
Revises: 342828f129b9
Create Date: 2016-04-18 10:39:49.605138

"""

# revision identifiers, used by Alembic.
revision = '44b2ab3c0bb7'
down_revision = '342828f129b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_order', sa.Column('datetime_cancelled', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_order', 'datetime_cancelled')
    ### end Alembic commands ###
