"""Add soft-delete column to schedule orders

Revision ID: 48fc7ba887aa
Revises: 24f44dfc7b3b
Create Date: 2016-04-10 07:25:44.998170

"""

# revision identifiers, used by Alembic.
revision = '48fc7ba887aa'
down_revision = '24f44dfc7b3b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_order', sa.Column('active', sa.Boolean(), server_default='1', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_order', 'active')
    ### end Alembic commands ###
