"""Added Drinks column, which wasn't in the first dump we got

Revision ID: 4e2abc6d63e6
Revises: 8f73ccc4fcb
Create Date: 2015-10-19 07:07:28.223009

"""

# revision identifiers, used by Alembic.
revision = '4e2abc6d63e6'
down_revision = '8f73ccc4fcb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Class_description', sa.Column('wine', sa.String(length=255), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Class_description', 'wine')
    ### end Alembic commands ###
