"""Remove order in shop product and replace with the unwieldy row/column again :/

Revision ID: 4f786f3c132b
Revises: 2d4ea6b57d6e
Create Date: 2016-03-20 07:11:09.422825

"""

# revision identifiers, used by Alembic.
revision = '4f786f3c132b'
down_revision = '2d4ea6b57d6e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shop_product', sa.Column('column', sa.Integer(), nullable=True))
    op.add_column('Shop_product', sa.Column('row', sa.Integer(), nullable=True))
    op.drop_column('Shop_product', 'order')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permission', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('Shop_product', sa.Column('order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('Shop_product', 'row')
    op.drop_column('Shop_product', 'column')
    op.create_table('backup_Class_description',
    sa.Column('description_id', mysql.INTEGER(display_width=11), server_default=sa.text(u"'0'"), autoincrement=False, nullable=False),
    sa.Column('order', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('abbr', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.LONGTEXT(), nullable=False),
    sa.Column('menu', mysql.LONGTEXT(), nullable=False),
    sa.Column('knife_level', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('veggie_level', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('dairy_level', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('wheat_level', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('cost_override', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('wine', mysql.VARCHAR(length=255), nullable=False),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('gift_certificate',
    sa.Column('certificate_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('campus_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('sender_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sender_email', mysql.VARCHAR(length=75), nullable=True),
    sa.Column('sender_phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('amount_to_give', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('recipient_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('recipient_email', mysql.VARCHAR(length=75), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('giftcard', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('date_sent', sa.DATE(), nullable=True),
    sa.Column('name_on_envelope', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('street_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('zip_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('creditcard_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('paid_with', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('expiration_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], [u'Class_campus.campus_id'], name=u'gift_certificate_ibfk_1'),
    sa.PrimaryKeyConstraint('certificate_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('forgot_password_links')
    ### end Alembic commands ###
