"""empty message

Revision ID: 512c88e1b54d
Revises: 5930c16d1a8c
Create Date: 2016-06-06 11:44:10.260864

"""

# revision identifiers, used by Alembic.
revision = '512c88e1b54d'
down_revision = '5930c16d1a8c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Class_campus', sa.Column('abbreviation', sa.String(length=6), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Class_campus', 'abbreviation')
    ### end Alembic commands ###
