"""empty message

Revision ID: 53358d10ac88
Revises: 150a70fbe43b
Create Date: 2015-10-13 23:44:23.504554

"""

# revision identifiers, used by Alembic.
revision = '53358d10ac88'
down_revision = '150a70fbe43b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_order', sa.Column('no_show', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_order', 'no_show')
    ### end Alembic commands ###
