"""Added "checked-in" flag to shopping cart instance items

Revision ID: 53944822f490
Revises: 433267c1db40
Create Date: 2015-12-08 17:51:50.116301

"""

# revision identifiers, used by Alembic.
revision = '53944822f490'
down_revision = '433267c1db40'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_instance_item', sa.Column('checked_in', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list_instance_item', 'checked_in')
    ### end Alembic commands ###
