"""empty message

Revision ID: 568a1c315cfb
Revises: 4367b53299c3
Create Date: 2016-06-08 11:00:17.927729

"""

# revision identifiers, used by Alembic.
revision = '568a1c315cfb'
down_revision = '4367b53299c3'

# standard imports
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# custom imports
from sqlalchemy import event
from sqlalchemy.orm import sessionmaker, Session as BaseSession
from flask_sqlalchemy import _SessionSignalEvents
from hipcooks import models

try:
    event.remove(BaseSession, 'before_commit', _SessionSignalEvents.session_signal_before_commit)
    event.remove(BaseSession, 'after_commit', _SessionSignalEvents.session_signal_after_commit)
    event.remove(BaseSession, 'after_rollback', _SessionSignalEvents.session_signal_after_rollback)
except:
    pass

Session = sessionmaker()

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_instance_item', sa.Column('is_one_off_item', sa.Boolean(), nullable=True))
    ### end Alembic commands ###

    bind = op.get_bind()
    session = Session(bind=bind)
    for instance_item in session.query(models.ShoppingListInstanceItem).all():
        if instance_item.class_id and instance_item.category:
            instance_item.is_one_off_item = True
            session.add(instance_item)

    session.commit()


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list_instance_item', 'is_one_off_item')
    ### end Alembic commands ###
