"""Add photo album/studio linkage

Revision ID: 57d0aa35f4d2
Revises: 284051baedc0
Create Date: 2016-03-06 07:36:20.142586

"""

# revision identifiers, used by Alembic.
revision = '57d0aa35f4d2'
down_revision = '284051baedc0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Class_album', sa.Column('campus_id', sa.Integer(), nullable=True))
    op.alter_column('Class_album', 'name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.create_foreign_key(None, 'Class_album', 'Class_campus', ['campus_id'], ['campus_id'])
    op.add_column('Class_photo', sa.Column('album_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Class_photo', 'Class_album', ['album_id'], ['album_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Class_photo', type_='foreignkey')
    op.drop_column('Class_photo', 'album_id')
    op.drop_constraint(None, 'Class_album', type_='foreignkey')
    op.alter_column('Class_album', 'name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.drop_column('Class_album', 'campus_id')
    ### end Alembic commands ###
