"""Added active/deleted flag

Revision ID: 5aa65bc2c37b
Revises: 53944822f490
Create Date: 2015-12-08 19:12:58.238701

"""

# revision identifiers, used by Alembic.
revision = '5aa65bc2c37b'
down_revision = '53944822f490'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_instance', sa.Column('active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list_instance', 'active')
    ### end Alembic commands ###
