"""Foreign-key the comments table to staff instead of users.

Revision ID: 5e7caa17d8b
Revises: 1482e7378ad7
Create Date: 2015-10-15 23:41:44.865020

"""

# revision identifiers, used by Alembic.
revision = '5e7caa17d8b'
down_revision = '1482e7378ad7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_report_comment', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'class_report_comment_ibfk_2', 'class_report_comment', type_='foreignkey')
    op.create_foreign_key(None, 'class_report_comment', 'Class_teacher', ['teacher_id'], ['user_id'])
    op.drop_column('class_report_comment', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_report_comment', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'class_report_comment', type_='foreignkey')
    op.create_foreign_key(u'class_report_comment_ibfk_2', 'class_report_comment', 'auth_user', ['user_id'], ['id'])
    op.drop_column('class_report_comment', 'teacher_id')
    ### end Alembic commands ###
