"""Add setup review column, which was not fully apparent from the mockups

Revision ID: 8f73ccc4fcb
Revises: 5e7caa17d8b
Create Date: 2015-10-16 19:07:49.072125

"""

# revision identifiers, used by Alembic.
revision = '8f73ccc4fcb'
down_revision = '5e7caa17d8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_report', sa.Column('setup_review', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gift_certificate_order', 'zip_code')
    op.drop_column('gift_certificate_order', 'street_address')
    op.drop_column('gift_certificate_order', 'state')
    op.drop_column('gift_certificate_order', 'name_on_envelope')
    op.drop_column('gift_certificate_order', 'city')
    op.drop_column('class_report', 'setup_review')
    ### end Alembic commands ###
