"""empty message

Revision ID: f45baecadb0
Revises: 44b2ab3c0bb7
Create Date: 2016-04-18 15:42:09.895474

"""

# revision identifiers, used by Alembic.
revision = 'f45baecadb0'
down_revision = '44b2ab3c0bb7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_instance', sa.Column('last_updated', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list_instance', 'last_updated')
    ### end Alembic commands ###
