"""empty message

Revision ID: f59eaec6560
Revises: 15270308e5ab
Create Date: 2015-10-14 18:20:32.757804

"""

# revision identifiers, used by Alembic.
revision = 'f59eaec6560'
down_revision = '15270308e5ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_report', sa.Column('draft', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_report', 'draft')
    ### end Alembic commands ###
